### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by sushiljain1989** [frenetic-lang/fattire#9]
Hi,

I am trying to install FatTire in Ubuntu 16.04 and I have tried in 14.04 as well. But it is not working and throws error. Find screenshot for details.
Could anyone help me on this ?

~Sushil

![fattire_4_github](https://cloud.githubusercontent.com/assets/4305242/19734355/8bdd29ce-9ba7-11e6-979c-32045f487b63.png)

**Comment by jnfoster** [comment]
Hi Sushil,

FatTire is not being actively developed or maintained. It should install against older version of Frenetic but you'd have to install it manually. It's possible to pin opam to a specific GitHub hash, which might make it easier.

Sorry about that.

-N
